services:
  moodle:
    image: derkora/moodle:latest
    container_name: moodle
    ports:
      - "80:80"
    volumes:
      - moodledata:/var/www/moodledata
      - moodle_data:/var/www/html
    environment:
      - MOODLE_DATABASE_HOST=moodle_db
      - MOODLE_DATABASE_NAME=moodle
      - MOODLE_DATABASE_USER=${MOODLE_DATABASE_USER}
      - MOODLE_DATABASE_PASSWORD=${MOODLE_DATABASE_PASSWORD}
    depends_on:
      - moodle_db
    restart: always 
    networks:
      - moodle-network

  moodle_db:
    image: mariadb:10.11
    container_name: moodle_db
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=moodle
      - MYSQL_USER=${MOODLE_DATABASE_USER}
      - MYSQL_PASSWORD=${MOODLE_DATABASE_PASSWORD}
    volumes:
      - moodle_db_data:/var/lib/mysql
    restart: always 
    networks:
      - moodle-network

volumes:
  moodle_data:
  moodledata:
  moodle_db_data:

networks:
  moodle-network:
    external: true