# Use the official PHP 8.3 image as a base
# Stage 1: Build stage
FROM php:8.3-cli-alpine AS builder

# Set environment variables for Moodle 5.0?
ENV MOODLE_VERSION=500
ENV MOODLE_GIT_REPO=https://github.com/moodle/moodle.git


